/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_guillermoespinal;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class lb7_principal extends javax.swing.JFrame {

    /**
     * Creates new form lb7_principal
     */
    public lb7_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearparada = new javax.swing.JDialog();
        sp_angulo = new javax.swing.JSpinner();
        sp_distancia = new javax.swing.JSpinner();
        tf_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_guardar = new javax.swing.JButton();
        jd_elegirbus = new javax.swing.JDialog();
        bt_seguir = new javax.swing.JButton();
        cb_buses = new javax.swing.JComboBox<>();
        jd_crearbusito = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        bt_guardarbus = new javax.swing.JButton();
        tf_id = new javax.swing.JTextField();
        sp_velocidad = new javax.swing.JSpinner();
        bt_color = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_placa = new javax.swing.JTextField();
        jd_estudiantes = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        bt_guardarestudiantes = new javax.swing.JButton();
        tf_estunombre = new javax.swing.JTextField();
        cb_paradas = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_edad = new javax.swing.JTextField();
        tf_cuenta = new javax.swing.JFormattedTextField();
        jd_elegirestudiantes = new javax.swing.JDialog();
        cb_estudiantes = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        bt_addestu = new javax.swing.JButton();
        jd_simulacion = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_tabla = new javax.swing.JTable();
        pb_tiempo = new javax.swing.JProgressBar();
        bt_empezar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jDialog7 = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        sp_angulo.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 360.0d, 1.0d));

        sp_distancia.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Distancia desde Unitec");

        jLabel3.setText("Angulo");

        bt_guardar.setText("Guardar");
        bt_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crearparadaLayout = new javax.swing.GroupLayout(jd_crearparada.getContentPane());
        jd_crearparada.getContentPane().setLayout(jd_crearparadaLayout);
        jd_crearparadaLayout.setHorizontalGroup(
            jd_crearparadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearparadaLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jd_crearparadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearparadaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)
                        .addComponent(sp_angulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_crearparadaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_crearparadaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(sp_distancia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(423, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearparadaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_guardar)
                .addGap(140, 140, 140))
        );
        jd_crearparadaLayout.setVerticalGroup(
            jd_crearparadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearparadaLayout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(jd_crearparadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(51, 51, 51)
                .addGroup(jd_crearparadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(17, 17, 17)
                .addGroup(jd_crearparadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sp_angulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(bt_guardar)
                .addGap(94, 94, 94))
        );

        bt_seguir.setText("Seguir");
        bt_seguir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_seguirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_elegirbusLayout = new javax.swing.GroupLayout(jd_elegirbus.getContentPane());
        jd_elegirbus.getContentPane().setLayout(jd_elegirbusLayout);
        jd_elegirbusLayout.setHorizontalGroup(
            jd_elegirbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_elegirbusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_seguir)
                .addGap(38, 38, 38))
            .addGroup(jd_elegirbusLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(cb_buses, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jd_elegirbusLayout.setVerticalGroup(
            jd_elegirbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_elegirbusLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(cb_buses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(bt_seguir)
                .addGap(49, 49, 49))
        );

        jLabel4.setText("ID :");

        bt_guardarbus.setText("Guardar");
        bt_guardarbus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardarbusMouseClicked(evt);
            }
        });

        sp_velocidad.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        bt_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_colorMouseClicked(evt);
            }
        });

        jLabel5.setText("Color :");

        jLabel6.setText("Velocidad :");

        jLabel7.setText("Placa :");

        javax.swing.GroupLayout jd_crearbusitoLayout = new javax.swing.GroupLayout(jd_crearbusito.getContentPane());
        jd_crearbusito.getContentPane().setLayout(jd_crearbusitoLayout);
        jd_crearbusitoLayout.setHorizontalGroup(
            jd_crearbusitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearbusitoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jd_crearbusitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearbusitoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(bt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jd_crearbusitoLayout.createSequentialGroup()
                        .addGroup(jd_crearbusitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearbusitoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_crearbusitoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(tf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jd_crearbusitoLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addComponent(bt_guardarbus)
                        .addGap(40, 40, 40))))
        );
        jd_crearbusitoLayout.setVerticalGroup(
            jd_crearbusitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearbusitoLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jd_crearbusitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_crearbusitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearbusitoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_guardarbus)
                        .addGap(39, 39, 39))
                    .addGroup(jd_crearbusitoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jd_crearbusitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_crearbusitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(jd_crearbusitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sp_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(54, 54, 54))))
        );

        jLabel8.setText("Nombre :");

        bt_guardarestudiantes.setText("Guardar");
        bt_guardarestudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardarestudiantesMouseClicked(evt);
            }
        });

        jLabel9.setText("Numero de cuenta :");

        jLabel10.setText("Nombre :");

        jLabel11.setText("Edad :");

        try {
            tf_cuenta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jd_estudiantesLayout = new javax.swing.GroupLayout(jd_estudiantes.getContentPane());
        jd_estudiantes.getContentPane().setLayout(jd_estudiantesLayout);
        jd_estudiantesLayout.setHorizontalGroup(
            jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_estudiantesLayout.createSequentialGroup()
                .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_estudiantesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_guardarestudiantes))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_estudiantesLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_estudiantesLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_estudiantesLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(tf_estunombre, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_estudiantesLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 217, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
            .addGroup(jd_estudiantesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_estudiantesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cb_paradas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jd_estudiantesLayout.setVerticalGroup(
            jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_estudiantesLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_estunombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(cb_paradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(34, 34, 34)
                .addComponent(bt_guardarestudiantes)
                .addGap(28, 28, 28))
        );

        jButton1.setText("Simular");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        bt_addestu.setText("Selecionar");
        bt_addestu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_addestuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_elegirestudiantesLayout = new javax.swing.GroupLayout(jd_elegirestudiantes.getContentPane());
        jd_elegirestudiantes.getContentPane().setLayout(jd_elegirestudiantesLayout);
        jd_elegirestudiantesLayout.setHorizontalGroup(
            jd_elegirestudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_elegirestudiantesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(cb_estudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_elegirestudiantesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_elegirestudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_addestu)
                    .addComponent(jButton1))
                .addGap(28, 28, 28))
        );
        jd_elegirestudiantesLayout.setVerticalGroup(
            jd_elegirestudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_elegirestudiantesLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(cb_estudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(bt_addestu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(58, 58, 58))
        );

        jt_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre de Parada", "Tiempo", "Estudiantes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_tabla);

        bt_empezar.setText("empezar");
        bt_empezar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_empezarMouseClicked(evt);
            }
        });

        jLabel12.setText("jLabel12");

        javax.swing.GroupLayout jd_simulacionLayout = new javax.swing.GroupLayout(jd_simulacion.getContentPane());
        jd_simulacion.getContentPane().setLayout(jd_simulacionLayout);
        jd_simulacionLayout.setHorizontalGroup(
            jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_simulacionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12)
                .addGap(54, 54, 54)
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addComponent(pb_tiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_simulacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_empezar)
                .addGap(75, 75, 75))
        );
        jd_simulacionLayout.setVerticalGroup(
            jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_simulacionLayout.createSequentialGroup()
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel12)))
                .addGap(35, 35, 35)
                .addComponent(pb_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(bt_empezar)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout jDialog7Layout = new javax.swing.GroupLayout(jDialog7.getContentPane());
        jDialog7.getContentPane().setLayout(jDialog7Layout);
        jDialog7Layout.setHorizontalGroup(
            jDialog7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog7Layout.setVerticalGroup(
            jDialog7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Crear");

        jMenuItem1.setText("Crear paradas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Crear estudiantes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Crear buses");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Crear Parada");

        jMenuItem4.setText("Simular");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_colorMouseClicked
        /*  Color c = JColorChooser.showDialog(this,"Selecione color", Color.yellow);
        bt_color.setForeground(c);
        bt_color.setBackground(c);*/
        bt_color.setBackground(JColorChooser.showDialog(this,"Seleccione un color",Color.yellow));
    }//GEN-LAST:event_bt_colorMouseClicked

    private void bt_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarMouseClicked
        try {
            String nombre = tf_nombre.getText();
            Double dist = (Double) sp_distancia.getValue();
            Double angulo = (Double) sp_angulo.getValue();
            parada parada = new parada(nombre, dist, angulo);
            adminParadas ap = new adminParadas("./paradas.cbm");
            ap.cargarArchivo();
            ap.addParada(parada);
            ap.escribirArchivo();
            JOptionPane.showMessageDialog(this, "Se creo la parada");
            tf_nombre.setText("");
            sp_angulo.setValue(1);
            sp_distancia.setValue(1);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se pudo crear la parada");
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_bt_guardarMouseClicked

    private void bt_guardarbusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarbusMouseClicked
        try {
            String placa = tf_placa.getText();
            int id = Integer.parseInt(tf_id.getText());
            Color color = bt_color.getBackground();
            double velocidad = (Double) sp_velocidad.getValue();
            bus bus = new bus(id, placa, color, velocidad);
            adminBuses ab = new adminBuses("./buses.cbm");
            ab.cargarArchivo();
            ab.addBuses(bus);
            ab.escribirArchivo();
            JOptionPane.showMessageDialog(this,"se creo el bus");
            tf_placa.setText("");
            tf_id.setText("");
            sp_velocidad.setValue(1);
            bt_color.setBackground(Color.WHITE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se pudo crear el bus vuelva a intentarlo");
            e.printStackTrace();
        }
                
        
    }//GEN-LAST:event_bt_guardarbusMouseClicked

    private void bt_guardarestudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarestudiantesMouseClicked
        try {
            String nombre = tf_estunombre.getText();
            int edad = Integer.parseInt(tf_edad.getText());
            int cuenta = Integer.parseInt(tf_cuenta.getText());
            parada parada = (parada) cb_paradas.getSelectedItem();
            estudiantes estudiante = new estudiantes(nombre, edad, cuenta, parada);
            adminEstudiantes ae = new adminEstudiantes("./estudiantes.cbm");
            ae.cargarArchivo();
            ae.addEstudiantes(estudiante);
            ae.escribirArchivo();
            JOptionPane.showMessageDialog(this, "Se creo el estudiante");
            tf_estunombre.setText("");
            tf_edad.setText("");
            tf_cuenta.setText("");
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"no se pudo crear el estudiante vuelva a intentarlo");
            e.printStackTrace();
        }
        
        
        
        
    }//GEN-LAST:event_bt_guardarestudiantesMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     
       
       jd_crearparada.setModal(true);
       jd_crearparada.pack();
       jd_crearparada.setVisible(true);
       jd_crearparada.setEnabled(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        cb_paradas.setModel(new DefaultComboBoxModel<>());
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)cb_paradas.getModel();
        adminParadas ap = new adminParadas("./paradas.cbm");
        ap.cargarArchivo();
        for (parada parada : ap.getParadas()) {
            modelo.addElement(parada);
        }
       cb_paradas.setModel(modelo);
       
       jd_estudiantes.setModal(true);
       jd_estudiantes.pack();
       jd_estudiantes.setVisible(true);
       jd_estudiantes.setEnabled(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         jd_crearbusito.setModal(true);
       jd_crearbusito.pack();
       jd_crearbusito.setVisible(true);
       jd_crearbusito.setEnabled(true);


    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       cb_buses.setModel(new DefaultComboBoxModel<>());
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)cb_buses.getModel();
        adminBuses ab = new adminBuses("./buses.cbm");
        ab.cargarArchivo();
        for (bus bus : ab.getBuses()) {
            modelo.addElement(bus);
        }
       cb_buses.setModel(modelo);
        
        jd_elegirbus.setModal(true);
          jd_elegirbus.pack();
       jd_elegirbus.setVisible(true);
       jd_elegirbus.setEnabled(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void bt_seguirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_seguirMouseClicked
        try {
            cb_estudiantes.setModel(new DefaultComboBoxModel<>());
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_estudiantes.getModel();
            adminEstudiantes ae = new adminEstudiantes("./estudiantes.cbm");
            ae.cargarArchivo();
            for (estudiantes estudiante : ae.getEstudiantes()) {
                modelo.addElement(estudiante);
            }
            
            bus_global = (bus) cb_buses.getSelectedItem();
            
            cb_estudiantes.setModel(modelo);
            
            jd_elegirestudiantes.setModal(true);
            jd_elegirestudiantes.pack();
            jd_elegirestudiantes.setVisible(true);
            jd_elegirestudiantes.setEnabled(true);
        } catch (Exception e) {
            
        }
       
        
        
        
    }//GEN-LAST:event_bt_seguirMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    jd_simulacion.setModal(true);
    jd_simulacion.pack();
    jd_simulacion.setVisible(true);
    jd_simulacion.setEnabled(true);

        
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void bt_addestuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addestuMouseClicked

        try {
            bus_global.addEstudiante((estudiantes) cb_estudiantes.getSelectedItem());
            JOptionPane.showMessageDialog(this, "Se creo el estudiante");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_bt_addestuMouseClicked

    private void bt_empezarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_empezarMouseClicked
        try {
            for (int i = 0; i < bus_global.getEstudiantes().size(); i++) {
                x_s.add(((estudiantes) bus_global.getEstudiantes().get(i)).getParada().getX());
                y_s.add(((estudiantes) bus_global.getEstudiantes().get(i)).getParada().getY());
            }
            parada parada = new parada("", 0, 0);
            HiloBarra hb= new HiloBarra(pb_tiempo,bus_global,parada);
            hb.start();
            
            
            /* for (int i = 0; i < x_s.size(); i++) {
            Double pasar = (Math.pow((x_s.get(i) - x_global), 2) + Math.pow((y_s.get(i)), 2));
            // System.out.println(pasar);
            distancias.add(Math.sqrt(pasar));
            }*/
            //PERAMEEEEE
            /* Collection<Double> distanciascc = distancias;
            distanciascc.se
            //perame perame
            for (Double x : distancias) {
            System.out.println(x);
            }
            
            double[]distanciass=ordenar(distancias);
            
            for (int i = 0; i < distancias.size(); i++) {
            double num= distanciass[i];
            distancias.set(i, num);
            }
            
            System.out.println("Perate wey \n");
            for (Double x : distancias) {
            System.out.println(x);
            }*/
        } catch (Exception e) {
            
            
            
        }
        
    }//GEN-LAST:event_bt_empezarMouseClicked

    
    public static double[] ordenar(ArrayList arreglo)
    {
        double[] arrglo=new double[arreglo.size()];
        for (int i = 0; i < arreglo.size(); i++) {
            arrglo[i]=(double) arreglo.get(i);
        }
      Double auxiliar;
      double[] arregloOrdenado;
      //ArrayList<Double> ordenado;
      
      for(int i = 1; i < arrglo.length; i++)
      {
        for(int j = 0;j < arrglo.length-i;j++)
        {
          if((arrglo[j]) > (arrglo[j+1]))
          {
            auxiliar = arrglo[j];
            arrglo[j] =arrglo[j+1];
            arrglo[j+1] = auxiliar;
          }   
        }
      }
      arregloOrdenado = arrglo;
      return arregloOrdenado;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lb7_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lb7_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lb7_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lb7_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lb7_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addestu;
    private javax.swing.JButton bt_color;
    private javax.swing.JButton bt_empezar;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JButton bt_guardarbus;
    private javax.swing.JButton bt_guardarestudiantes;
    private javax.swing.JButton bt_seguir;
    private javax.swing.JComboBox<String> cb_buses;
    private javax.swing.JComboBox<String> cb_estudiantes;
    private javax.swing.JComboBox<String> cb_paradas;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jd_crearbusito;
    private javax.swing.JDialog jd_crearparada;
    private javax.swing.JDialog jd_elegirbus;
    private javax.swing.JDialog jd_elegirestudiantes;
    private javax.swing.JDialog jd_estudiantes;
    private javax.swing.JDialog jd_simulacion;
    private javax.swing.JTable jt_tabla;
    private javax.swing.JProgressBar pb_tiempo;
    private javax.swing.JSpinner sp_angulo;
    private javax.swing.JSpinner sp_distancia;
    private javax.swing.JSpinner sp_velocidad;
    private javax.swing.JFormattedTextField tf_cuenta;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_estunombre;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_placa;
    // End of variables declaration//GEN-END:variables
    double x_global;
    double y_global;
    ArrayList<Double>x_s=new ArrayList<>();
    ArrayList<Double>y_s=new ArrayList<>();
    ArrayList<Double>distancias= new ArrayList<>();
    Double next_dist;
    bus bus_global;
    

            

}
